import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { AppProvider } from '@/context/app_context'
import Cart from '@/components/Cart'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}  >
        <AppProvider>

          <Header />
          <Sidebar />
          <main className='mx-auto min-h-screen max-w-screen-xl items-center relative gap-8 px-4 sm:px-6 lg:px-8'>
            <div className='absolute right-10 top-0'>
              <Cart />
            </div>
            {children}
          </main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  )
}
